package routes

import "testing"

// The embedded table is generated by `parity vendor-routes --write` from each
// service's measured parity backend. These tests pin the facts the proxy
// depends on, so a regeneration that changed them fails here rather than
// misrouting a client's traffic.

func TestTheTableLoadsAndKnowsTheVendors(t *testing.T) {
	known := Known()
	if len(known) < 10 {
		t.Fatalf("only %d services in the route table: %v", len(known), known)
	}
	for _, want := range []string{"stripe", "fineract", "google-calendar", "google-drive", "google-identity"} {
		if _, ok := For(want); !ok {
			t.Errorf("%s has no route", want)
		}
	}
}

func TestFineractClaimsTheConnectorDeploymentHosts(t *testing.T) {
	entries, ok := For("fineract")
	if !ok {
		t.Fatal("fineract has no routes")
	}
	want := map[string]bool{
		"mifos.mifos.gazelle.test": false,
		"leopard.mifos.io":         false,
	}
	for _, entry := range entries {
		if _, known := want[entry.Host]; known {
			want[entry.Host] = true
		}
		if len(entry.Paths) != 0 {
			t.Errorf("fineract host %q should claim the whole host, got paths %v", entry.Host, entry.Paths)
		}
	}
	for host, found := range want {
		if !found {
			t.Errorf("fineract does not claim %q; entries = %+v", host, entries)
		}
	}
}

func TestASingleHostVendorClaimsTheWholeHost(t *testing.T) {
	entries, ok := For("stripe")
	if !ok || len(entries) != 1 {
		t.Fatalf("stripe entries = %+v", entries)
	}
	if entries[0].Host != "api.stripe.com" {
		t.Errorf("stripe host = %q", entries[0].Host)
	}
	if len(entries[0].Paths) != 0 {
		t.Errorf("stripe should claim the whole host, got paths %v", entries[0].Paths)
	}
}

// Google is why the table exists: three services on one hostname, plus an
// identity surface spread across four hosts.
func TestGoogleIsSplitByHostAndPrefix(t *testing.T) {
	for _, tc := range []struct {
		service string
		host    string
		path    string
	}{
		{"google-calendar", "www.googleapis.com", "/calendar/v3"},
		{"google-drive", "www.googleapis.com", "/drive/v3"},
		{"google-drive", "www.googleapis.com", "/upload/drive/v3/files"},
		{"google-identity", "www.googleapis.com", "/oauth2/v3"},
		// The fact a hand-written table got wrong: Google serves token
		// introspection from oauth2.googleapis.com, not www.googleapis.com.
		{"google-identity", "oauth2.googleapis.com", "/tokeninfo"},
		{"google-identity", "accounts.google.com", "/o/oauth2/v2/auth"},
	} {
		entries, ok := For(tc.service)
		if !ok {
			t.Errorf("%s has no routes", tc.service)
			continue
		}
		found := false
		for _, e := range entries {
			if e.Host != tc.host {
				continue
			}
			for _, p := range e.Paths {
				if p == tc.path {
					found = true
				}
			}
		}
		if !found {
			t.Errorf("%s does not claim %s%s; entries = %+v",
				tc.service, tc.host, tc.path, entries)
		}
	}
}

func TestAnUnknownServiceIsReportedRatherThanGuessed(t *testing.T) {
	if _, ok := For("no-such-vendor"); ok {
		t.Fatal("an unknown service should have no routes")
	}
}
